#!/bin/bash
#version 1.0

#MaunNgepain?
#MauRecode?MALUGOBLOK
#BUATSENDIRITOLOL

# Variables
b='\033[1m'
u='\033[4m'
bl='\E[30m'
r='\E[31m'
g='\E[32m'
bu='\E[34m'
m='\E[35m'
c='\E[36m'
w='\E[37m'
endc='\E[0m'
enda='\033[0m'
blue='\e[1;34m'
cyan='\e[1;36m'
red='\e[1;31m'

figlet Balikpapan Tools | lolcat

echo -e  "_____________________________________________________________"
echo -e  "Tools    : Balikpapan Security Team V 1.0 $white         " |lolcat
echo -e  "Author  : B4E_7 $white   " |lolcat
echo -e  "TEAM : BALIKPAPAN CYBER TEAM $white " |lolcat
echo -e  "Note : Author Atau Pembuat Tools Tidak bertanggung jawab Jika ada masalah $white" |lolcat
echo -e  "Support : BalikpapanCyberKu $white " |lolcat
echo -e  "_____________________________________________________________"

###################################################
# CTRL + C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "
echo -e $cyan"[#]> Thanks"
sleep 1
echo ""
echo -e $white"[#]> see you gaes :)..."
sleep 1
exit
}

lagi=1
while [ $lagi -lt 6 ];
do
echo ""
echo -e $b "1.  Nmap${enda}";
echo -e "============================" | lolcat
echo -e $r "2.  Admin-finder${endc}";
echo -e "============================" | lolcat
echo -e $g "3.  RED_HAWK${endc}";
echo -e "============================" | lolcat
echo -e $c "4   Lazymux${endc}";
echo -e "============================" | lolcat
echo -e $r"5.  Tools-X${endc}";
echo -e "============================" | lolcat
echo -e $r"6. Locator${endc}";
echo -e "============================" | lolcat
echo -e $r"7. D-TECT-1${endc}";
echo -e "============================" | lolcat
echo -e $r"8. shellphish${endc}";
echo -e "============================" | lolcat
echo -e $r"9. Xerxes-1${endc}";
echo -e "============================" | lolcat
echo -e $r"10.LITESCRIPT${endc}";
echo -e "============================" | lolcat
echo -e $r"11.fsociety${endc}";
echo -e "============================" | lolcat
echo -e $r "12. Exit${endc}";
echo ""
echo -e "╭─B4e_7" |lolcat
read -p "╰─#" pil;

# Nmap

case $pil in
1) pkg install nmap
echo -e  "${y} {1} Masukkan Web${endc}:"
read web
nmap $web
echo


;;

# admin-finder

2) git clone  https://github.com/the-c0d3r/admin-finder.git
echo -e "${y} cara menggunakan admin finder"
echo -e "${y} cd admin-finder"
echo -e "${y} python admin-finder.py"


;;

#RED_HAWK

3) git clone https://github.com/Tuhinshubhra/RED_HAWK
echo -e "${y} Installer RED_HAWK..."
echo -e "${y} cd RED_HAWK"
echo -e "${y} php RED_HAWK.php"


;;

#Lazymux

4) git clone https://github.com/Gameye98/Lazymux
echo -e "${y} Installer Lazymux..."
echo -e "${y} cd Lazymux"
echo -e "${y} python lazymux.py"


;;

#Tools-X

5) git clone https://github.com/Rajkumrdusad/Tool-X
echo -e "${y} Installer Tool-X..."
echo -e "${y} cd Tool-X"
echo -e "${y} sh install.aex"


;;

#locator
6) git clone https://github.com/thelinuxchoice/locator
echo -e "${y} Installer Locator..."
echo -e "${y} cd Locator"
echo -e "${y} bash locator.sh"


;;

#D-TECT-1
7) git clone https://github.com/shawarkhanethicalhacker/D-TECT-1
echo -e "${y} Installer D-TECT-1..."
echo -e "${y} cd D-TECT-1"
echo -e "${y} python2 d-tect.py"


;;

#shellphish
8) git clone https://github.com/thelinuxchoice/shellphish
echo -e "${y} Installer shellphish"
echo -e "${y} cd shellphish"
echo -e "${y} bash shellphish.sh"


;;

#Xerxes-1
9) git clone https://github.com/ttbooter/Xerxes-1
echo -e "${y} SUDAH DI INSTALL CUY.."


;;

#LITESCRIPT
10) git clone https://github.com/4L13199/LITESCRIPT
echo -e "${y} SUDAH DI INSTALL CUY.."


;;

#fsociety
11) git clone https://github.com/Manisso/fsociety
echo -e "${y} SUDAH DI INSTALL CUY.."


;;

12) echo "No System Is Safe Expect Us : B4E_7" | lolcat
exit


;;

*) echo "sorry, pilihan yang anda cari tidak ada"
esac
done
done
